spring:
  application:
    name: landa-springcloud-demo
  cloud:
    client:
      hostname: springcloud-demo
#  jpa:
#    database: MYSQL
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: false
#  datasource:
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    driverClassName: com.mysql.jdbc.Driver
#    filters: stat,wall,log4j
#    initialSize: 5
#    maxActive: 20
#    maxPoolPreparedStatementPerConnectionSize: 20
#    maxWait: 60000
#    minEvictableIdleTimeMillis: 300000
#    minIdle: 5
#    poolPreparedStatements: true
#    testOnBorrow: false
#    testOnReturn: false
#    testWhileIdle: true
#    timeBetweenEvictionRunsMillis: 60000
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://${mysql.host}:3306/spring_cloud?useUnicode=true&characterEncoding=utf-8
#    username: tenxcloud
#    password: tenxcloud
#    validationQuery: SELECT 1 FROM DUAL
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: guest
    password: guest
  zipkin:
    baseUrl: http://${trace.host}:9411/
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: org.springframework.cloud.netflix.hystrix.stream.HystrixStreamTask

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.host}:8761/eureka/
